# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('name_db', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meta_description', models.TextField(max_length=155, null=True)),
                ('ordre', models.IntegerField(blank=True, default=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('name_db', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('question', models.TextField(default='Question...', verbose_name='Votre question')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=155, null=True)),
                ('reponse', models.TextField(blank=True, null=True)),
                ('repondue', models.NullBooleanField(default=False)),
                ('affichage', models.NullBooleanField(default=False)),
                ('mail_demande', models.EmailField(blank=True, default='exemple@mail.com', max_length=254, null=True, verbose_name='Votre mail')),
                ('ordre', models.IntegerField(blank=True, default=10, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Categorie')),
            ],
        ),
    ]
