# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('name_db', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meta_description', models.TextField(max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('name_db', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('slug', models.SlugField(null=True)),
                ('meta_description', models.TextField(max_length=155, null=True)),
                ('reponse', models.TextField(null=True)),
                ('repondue', models.NullBooleanField(default=False)),
                ('affichage', models.NullBooleanField(default=False)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Categorie')),
            ],
        ),
    ]
