# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='meta_description',
            field=models.TextField(default='', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponse',
            field=models.TextField(default='', null=True),
        ),
    ]
