# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20160913_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mail_demande',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Categorie'),
        ),
    ]
