# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20160913_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mail_demande',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Votre mail'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='Votre question'),
        ),
    ]
