# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20160913_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mail_demande',
            field=models.EmailField(blank=True, default='exemple@mail.com', max_length=254, null=True, verbose_name='Votre mail'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='Question...', verbose_name='Votre question'),
        ),
    ]
