# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_db', models.CharField(max_length=50)),
                ('titre_article', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_db', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meta_description', models.TextField(blank=True, max_length=155)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Categorie'),
        ),
    ]
