# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='titre_page',
        ),
        migrations.AddField(
            model_name='article',
            name='name_db',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
