# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160913_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, default='', max_length=155),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='meta_description',
            field=models.TextField(blank=True, default='', max_length=155),
            preserve_default=False,
        ),
    ]
