# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160221_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_db', models.CharField(max_length=50)),
                ('titre_article', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Categorie')),
            ],
        ),
    ]
