branch-defaults:
  master:
    environment: envascenseur
    group_suffix: null
global:
  application_name: ascenseur
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: eu-west-1
  profile: eb-cli
  sc: git
