# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-19 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_db', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meta_description', models.TextField(blank=True, max_length=155, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('logo_defaut', models.ImageField(blank=True, default=None, null=True, upload_to='logos/categorie/')),
                ('texte_page', models.TextField(blank=True, default='\xe0 remplir')),
            ],
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_db', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=155, null=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='logos/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestataires.Categorie')),
            ],
        ),
    ]
