# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste_prestataires',
            name='meta_description',
            field=models.TextField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='liste_prestataires',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='type_prestataire',
            name='meta_description',
            field=models.TextField(max_length=155, null=True),
        ),
    ]
