# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-19 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='nom_db',
        ),
        migrations.RemoveField(
            model_name='prestataire',
            name='nom_db',
        ),
    ]
