# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0002_auto_20160913_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste_prestataires',
            name='meta_description',
            field=models.TextField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='liste_prestataires',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type_prestataire',
            name='meta_description',
            field=models.TextField(blank=True, max_length=155, null=True),
        ),
    ]
