# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0003_auto_20160913_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pre_article',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='pre_Article',
        ),
        migrations.DeleteModel(
            name='pre_Categorie',
        ),
    ]
