# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0004_auto_20160914_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_prestataire',
            name='id',
        ),
        migrations.AddField(
            model_name='liste_prestataires',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='type_prestataire',
            name='nom_db',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
