# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0005_auto_20160916_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liste_prestataires',
            name='id',
        ),
        migrations.AddField(
            model_name='liste_prestataires',
            name='nom_db',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
