# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0006_auto_20160916_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_prestataire',
            old_name='nom_categorie',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='type_prestataire',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liste_prestataires',
            name='nom_db',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='type_prestataire',
            name='nom_db',
            field=models.CharField(max_length=200),
        ),
    ]
