# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0008_type_prestataire_logo_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_prestataire',
            name='texte_page',
            field=models.TextField(blank=True),
        ),
    ]
