# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0009_type_prestataire_texte_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_prestataire',
            name='texte_page',
            field=models.TextField(blank=True, default='\xe0 remplir'),
        ),
    ]
